The purpose of this assignment is two-fold: (a) to have you engaged in independent learning concerning dashboard creation and interactive visualization methods, and (b) to enhance our knowledge overall in the class (including mine!) by engaging in peer instruction. More specifically, I want you to create an interactive dashboard and write a tutorial demonstration that shows multiple visualization techniques working together (e.g., combining line charts, bar charts, and scatter plots in an interactive interface). 

The purpose of using data visualization is to tell a story, and the purpose of writing up a demonstration is to teach someone else about what you have learned so that they can use it, too. Think of this as a worked example, something like a medium blog post that you have written up and are posting so that other data scientists can learn about the potential uses of this style of data exploration and visualization. You should be concise in your wording and clear in your demonstration. 

You will need to include the write-up and demonstrate in a new notebook, which you will be submitting. Your notebook should be primarily narrative, broken up by code cells that demonstrate the work that you're demonstrating. You should have the following main sections in your notebook (but feel free to use other subheadings as appropriate): 

Visualization Technique (25%) 

A narrative description of each visualization type in your dashboard 

A discussion of how these visualizations complement each other and when each should be used, Dashboard-specific considerations like interactivity options 

Visualization Library (25%) 

The dashboard framework and libraries you're using, and why they're suitable for this visualization. For instance, who created it? Is it open source? How do you install it? It is important to clarify that you should not use Altair or Matplotlib for this assignment.

A discussion of the general approach and limitations of this framework. For instance, is it declarative or procedural? Does it integrate with Jupyter? Why did you decide to use this framework (especially if there are other options)? 

Demonstration (50%) 

The dataset you picked and the instructions for cleaning the dataset. You should pick a suitable dataset to demonstrate multiple visualization types and interactive features working together. 

The quality of your demonstration. First, demonstrate building basic dashboard components, then show how to implement interactivity and advanced features. This is the "meat" of the assignment. For reference, you should have at least 4 graph types in your dashboard that work together to tell a cohesive story.

Dashboard expected: Multiple visualizations are visible on a single screen with interactive features that affect multiple visualizations simultaneously.

Deliverables 

Final Dashboard 

Complete dashboard source code. Code Repository (git repo or zip file)
All necessary dependencies and assets/datasets
The dashboard should be publicly available
Create a video demonstration showcasing the key interactions of your dashboard, keeping it under one minute.
Notebook 

Written tutorial covering a narrative description, the libraries you're using, and a demonstration of all visualizations and interactions. Include screenshots and code snippets Troubleshooting of any common errors you encountered.  
Deploy instructions for your dashboard

In [276]:
import pandas as pd
import plotly.express as px
import panel as pn

In [277]:
# variables for filter button sizes
filter_controls_width = 200
filter_width = filter_controls_width - 20

In [278]:
# have to load df first because the the pn.depends decorator needs to reference a global df.  Should look for a better way to do this
pn.extension('plotly','tabulator')


df = pd.read_csv('data/heart_failure_clinical_records_dataset.csv')

display(df)

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
0,75.0,0,582,0,20,1,265000.00,1.9,130,1,0,4,1
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1,0,6,1
2,65.0,0,146,0,20,0,162000.00,1.3,129,1,1,7,1
3,50.0,1,111,0,20,0,210000.00,1.9,137,1,0,7,1
4,65.0,1,160,1,20,0,327000.00,2.7,116,0,0,8,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,62.0,0,61,1,38,1,155000.00,1.1,143,1,1,270,0
295,55.0,0,1820,0,38,0,270000.00,1.2,139,0,0,271,0
296,45.0,0,2060,1,60,0,742000.00,0.8,138,0,0,278,0
297,45.0,0,2413,0,38,0,140000.00,1.4,140,1,1,280,0
298,50.0,0,196,0,45,0,395000.00,1.6,136,1,1,285,0

In [279]:
# variables are age, anaemia, creatinine_phosphokinase, diabetes, ejection_fraction, high_blood_pressure, platelets, serum_creatinine, serum_sodium, sex, smoking, time, and DEATH_EVENT
# target variable is DEATH_EVENT

numeric_cols = [
    'age',
    'creatinine_phosphokinase',
    'ejection_fraction',
    'platelets',
    'serum_creatinine',
    'serum_sodium',
    'time'
]

In [280]:
# update categorical columns to be strings instead of integers
df['DEATH_EVENT_LABEL'] = df['DEATH_EVENT'].map({0: 'Survived', 1: 'Died'})
df['sex_label'] = df['sex'].map({0: 'Female', 1: 'Male'})
df['smoking_label'] = df['smoking'].map({0: 'Non-Smoker', 1: 'Smoker'})
df['diabetes_label'] = df['diabetes'].map({0: 'Non-Diabetic', 1: 'Diabetic'})
df['high_blood_pressure_label'] = df['high_blood_pressure'].map({0: 'No High Blood Pressure', 1: 'High Blood Pressure'})

In [281]:
display(df)

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT,DEATH_EVENT_LABEL,sex_label,smoking_label,diabetes_label,high_blood_pressure_label
0,75.0,0,582,0,20,1,265000.00,1.9,130,1,0,4,1,Died,Male,Non-Smoker,Non-Diabetic,High Blood Pressure
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1,0,6,1,Died,Male,Non-Smoker,Non-Diabetic,No High Blood Pressure
2,65.0,0,146,0,20,0,162000.00,1.3,129,1,1,7,1,Died,Male,Smoker,Non-Diabetic,No High Blood Pressure
3,50.0,1,111,0,20,0,210000.00,1.9,137,1,0,7,1,Died,Male,Non-Smoker,Non-Diabetic,No High Blood Pressure
4,65.0,1,160,1,20,0,327000.00,2.7,116,0,0,8,1,Died,Female,Non-Smoker,Diabetic,No High Blood Pressure
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,62.0,0,61,1,38,1,155000.00,1.1,143,1,1,270,0,Survived,Male,Smoker,Diabetic,High Blood Pressure
295,55.0,0,1820,0,38,0,270000.00,1.2,139,0,0,271,0,Survived,Female,Non-Smoker,Non-Diabetic,No High Blood Pressure
296,45.0,0,2060,1,60,0,742000.00,0.8,138,0,0,278,0,Survived,Female,Non-Smoker,Diabetic,No High Blood Pressure
297,45.0,0,2413,0,38,0,140000.00,1.4,140,1,1,280,0,Survived,Male,Smoker,Non-Diabetic,No High Blood Pressure
298,50.0,0,196,0,45,0,395000.00,1.6,136,1,1,285,0,Survived,Male,Smoker,Non-Diabetic,No High Blood Pressure

# Create Widgets

In [282]:
sex_filter = pn.widgets.Select(
    name='Sex Filter',
    options=['All', 'Male', 'Female'],
    value='All',
    width=filter_width
)

outcome_filter = pn.widgets.Select(
    name='Death Outcome Filter',
    options=['All', 'Survived', 'Died'],
    value='All',
    width=filter_width
)

hist_var = pn.widgets.Select(
    name='Histogram Variable',
    options=numeric_cols,
    value='age',
    width=filter_width
)

hist_bins = pn.widgets.IntSlider(
    name='Histogram Bins',
    start=5,
    end=30,
    value=15
)

box_var = pn.widgets.Select(
    name='Boxplot Variable',
    options=numeric_cols,
    value='ejection_fraction',
    width=filter_width
)

scatter_x = pn.widgets.Select(
    name='Scatterplot X Variable',
    options=numeric_cols,
    value='serum_creatinine',
    width=filter_width
)

scatter_y = pn.widgets.Select(
    name='Scatterplot Y Variable',
    options=numeric_cols,
    value='serum_sodium',
    width=filter_width
)

heatmap_vars = pn.widgets.MultiSelect(
    name='Heatmap Variables',
    options=numeric_cols,
    value=numeric_cols,
    size=7
)

# Functions

In [283]:

def build_title(base_title:str, sex_value:str, outcome_value:str) -> str:
    """
    Dynamically build the title based on the selected filters
    """
    filters = []
    if sex_value != 'All':
        filters.append(sex_value)
    if outcome_value != 'All':
        filters.append(outcome_value)
    
    if filters:
        return f'{base_title} with filters: {filters}'
    return base_title

def filter_df(df:pd.DataFrame, sex_value:str, outcome_value:str) -> pd.DataFrame:
    """
    Filter the dataframe based on suppled gender value and death outcome value
    """
    filtered_df = df.copy()
    
    if sex_value != 'All':
        filtered_df = filtered_df[filtered_df['sex_label']==sex_value]
    
    if outcome_value != 'All':
        filtered_df = filtered_df[filtered_df['DEATH_EVENT_LABEL']==outcome_value]
    
    return filtered_df

@pn.depends(hist_var, hist_bins, sex_filter, outcome_filter)
def make_histogram(variable:str, bins:int, sex_value:str, outcome_value:str):
    """
    Make a histogram based on the input variable, bins, kde, sex value, and outcome value
    """
    filtered_df = filter_df(df, sex_value, outcome_value)
    title = build_title(f'Histogram of {variable}', sex_value, outcome_value)

    fig = px.histogram(
        filtered_df,
        x = variable,
        nbins = bins,
        title=title
    )

    fig.update_layout(height=400)

    return pn.pane.Plotly(fig, sizing_mode='stretch_width')

@pn.depends(box_var, sex_filter, outcome_filter)
def make_boxplot(variable:str, sex_value:str, outcome_value:str):
    """
    """
    filtered_df = filter_df(df, sex_value, outcome_value)
    title = build_title(f'Boxplot of {variable}', sex_value, outcome_value)

    fig = px.box(
        filtered_df,
        x = 'DEATH_EVENT_LABEL',
        y = variable,
        title = title
    )
    fig.update_layout(height=400)

    return pn.pane.Plotly(fig, sizing_mode='stretch_width')

@pn.depends(scatter_x, scatter_y, sex_filter, outcome_filter)
def make_scatterplot(x_var:str, y_var:str, sex_value:str, outcome_value:str):
    """
    """
    filtered_df = filter_df(df, sex_value, outcome_value)
    title = build_title(f'Scatterplot of {x_var} vs {y_var}', sex_value, outcome_value)

    fig = px.scatter(
        filtered_df,
        x=x_var,
        y=y_var,
        hover_data=[
            'sex_label',
            'smoking_label',
            'diabetes_label',
            'high_blood_pressure_label'
        ],
        title=title
    )

    fig.update_layout(height=400)

    return pn.pane.Plotly(fig, sizing_mode='stretch_width')

@pn.depends(heatmap_vars, sex_filter, outcome_filter)
def make_heatmap(selected_vars, sex_value:str, outcome_value:str):
    """
    """
    filtered_df = filter_df(df, sex_value, outcome_value)

    selected_vars_list = list(selected_vars)
    if len(selected_vars_list) < 2:
        return pn.pane.Markdown("Please select at least 2 variables for the heatmap")
    
    title = build_title('Correlation Heatmap', sex_value, outcome_value)
    corr = filtered_df[selected_vars_list].corr()

    fig = px.imshow(
        corr,
        x=corr.columns,
        y=corr.index,
        aspect='auto',
        text_auto='.2f',
        color_continuous_scale='Viridis',
        title=title
    )

    fig.update_layout(height=400)

    return pn.pane.Plotly(fig, sizing_mode='stretch_width')

@pn.depends(sex_filter, outcome_filter)
def make_table(sex_value:str, outcome_value:str):
    """
    """
    filtered_df = filter_df(df, sex_value, outcome_value)

    return pn.widgets.Tabulator(filtered_df, pagination='local', page_size=10, sizing_mode='stretch_width')

# Bind functions to widgets and create Views

In [284]:
histogram_view = pn.Column(
    hist_var,
    hist_bins,
    make_histogram,
    sizing_mode='stretch_width'
)

boxplot_view = pn.Column(
    box_var,
    make_boxplot,
    sizing_mode='stretch_width'
)

scatter_view = pn.Column(
    scatter_x,
    scatter_y,
    make_scatterplot,
    sizing_mode='stretch_width'
)

heatmap_view = pn.Column(
    heatmap_vars,
    make_heatmap,
    sizing_mode='stretch_width'
)

table_view = pn.Column(
    make_table,
    sizing_mode='stretch_width'
)

In [285]:
filter_controls = pn.WidgetBox(
    'FILTERS',
    sex_filter,
    outcome_filter,
    width=filter_controls_width,
    sizing_mode='fixed'
)

tabs = pn.Tabs(
    ('Histogram', histogram_view),
    ('Box Plot', boxplot_view),
    ('Scatterplot', scatter_view),
    ('Heatmap', heatmap_view),
    ('Data Table', table_view),
    sizing_mode='stretch_width'
)

dashboard = pn.Row(
    filter_controls,
    tabs,
    sizing_mode='stretch_width'
)

# Display Dashboard

In [ ]:
# open this in the browser because it doesn't work in VS Code
dashboard.show(port=8080, open=True, threaded=True)

Launching server at http://localhost:8006

WARNING:bokeh.core.validation.check:W-1005 (FIXED_SIZING_MODE): 'fixed' sizing mode requires width and height to be set: Column(id='75107f32-ad0d-4b2e-a3c8-6aa04aaa100b', ...)
WARNING:bokeh.core.validation.check:W-1005 (FIXED_SIZING_MODE): 'fixed' sizing mode requires width and height to be set: Column(id='541f7e81-d617-4b87-b026-483fb05bc9e7', ...)
WARNING:bokeh.core.validation.check:W-1005 (FIXED_SIZING_MODE): 'fixed' sizing mode requires width and height to be set: Column(id='7ce83e84-ccaf-49b8-9ee3-fcc2063b0577', ...)